name: CI
run-name: ${{ github.actor }} is running the ALP CI

on: push

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Build
        run: echo "todo"

  build:
    needs:
      - check-format
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, macos-latest]
        BUILD_TYPE: [Debug, Release]
        cxx: [clang++]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Make Build Directory
        run: mkdir ${{ github.workspace }}/build

      - name: Configure CMake
        run: cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }}
        env:
          CXX: ${{ matrix.cxx }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build -j 16

  test:
    needs:
      - build
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, macos-latest]
        BUILD_TYPE: [Debug, Release]
        cxx: [clang++]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Make Build Directory
        run: mkdir ${{ github.workspace }}/build

      - name: Configure CMake
        run: cmake -DALP_BUILD_TESTING=ON -DALP_ENABLE_VERBOSE_OUTPUT=ON -S ${{ github.workspace }} -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }}
        env:
          CXX: ${{ matrix.cxx }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build -j 16

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -j 4 --rerun-failed --output-on-failure

  build_benchmark:
    needs:
      - test
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, macos-latest]
        BUILD_TYPE: [Release]
        cxx: [clang++]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Make Build Directory
        run: mkdir ${{ github.workspace }}/build

      - name: Configure CMake
        run: cmake -DALP_BUILD_BENCHMARKING=ON -S ${{ github.workspace }} -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }}
        env:
          CXX: ${{ matrix.cxx }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build -j 16

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -j 4

  build_full_dataset:
    needs:
      - test
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, macos-latest]
        BUILD_TYPE: [Release]
        cxx: [clang++]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Make Build Directory
        run: mkdir ${{ github.workspace }}/build

      - name: Configure CMake
        run: cmake -DALP_BUILD_BENCHMARKING=ON -S ${{ github.workspace }} -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }}
        env:
          CXX: ${{ matrix.cxx }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build -j 16
