name: CI
run-name: ${{ github.actor }} is running the ALP CI

on: push

env:
  BUILD_DIR: ${{ github.workspace }}/build
  PARALLEL_JOBS: 16

strategy:
  matrix:
    platform: [ ubuntu-latest, macos-latest ]
    BUILD_TYPE: [ Debug, Release ]
    cxx: [ clang++ ]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check Code Format
        run: echo "Format check TODO"

  build:
    needs: check-format
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir -p ${{ env.BUILD_DIR }}
          cmake -S . -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }}
          cmake --build ${{ env.BUILD_DIR }} -j ${{ env.PARALLEL_JOBS }}

  test:
    needs: build
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          ctest -j ${{ env.PARALLEL_JOBS }} --output-on-failure --rerun-failed

  build_benchmark:
    needs: test
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure and Build Benchmarks
        run: |
          mkdir -p ${{ env.BUILD_DIR }}
          cmake -S . -B ${{ env.BUILD_DIR }} -DALP_BUILD_BENCHMARKING=ON
          cmake --build ${{ env.BUILD_DIR }} -j ${{ env.PARALLEL_JOBS }}

  build_full_dataset:
    needs: test
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Full Dataset
        run: |
          mkdir -p ${{ env.BUILD_DIR }}
          cmake -S . -B ${{ env.BUILD_DIR }} -DALP_BUILD_BENCHMARKING=ON
          cmake --build ${{ env.BUILD_DIR }} -j ${{ env.PARALLEL_JOBS }}
